name: Update Theme Version

on:
  push:
    branches:
      - main # or master, depending on your default branch
    paths-ignore:
      - 'style.css' # Prevent infinite loop by ignoring commits to style.css

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update version number
        run: |
          # Get current version from style.css
          CURRENT_VERSION=$(grep -oP "Version: \K[0-9]+\.[0-9]+(\.[0-9]+)?" style.css)
          echo "Current version: $CURRENT_VERSION"
          
          # Split version into components
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]:-0}
          
          # Determine version update type from commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $COMMIT_MSG == *"[major]"* ]]; then
            ((MAJOR++))
            MINOR=0
            PATCH=0
            UPDATE_TYPE="major"
          elif [[ $COMMIT_MSG == *"[minor]"* ]]; then
            ((MINOR++))
            PATCH=0
            UPDATE_TYPE="minor"
          else
            ((PATCH++))
            UPDATE_TYPE="patch"
          fi
          
          # Create new version string
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version: $NEW_VERSION (${UPDATE_TYPE} update)"
          
          # Update style.css file
          sed -i "s/Version: ${CURRENT_VERSION}/Version: ${NEW_VERSION}/" style.css

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add style.css
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Bump version number [skip ci]"
          git push
